### ISSUE TITLE
the svn command need to replaced by the corresponding git one.

### ISSUE THREAD

**Issue by jfclere** [web-servers/xbuild#1]
https://github.com/web-servers/xbuild/blob/03c1faad0c2be9ecc7c02f6f82ce1087381413c4/tools/mkbrew.sh#L27

**Comment by jfclere** [comment]
See http://pkgs.devel.redhat.com/cgit/rpms/xbuild/tree/Makefile.common?h=jb-cs-httpd24-18-xb#n104 too :D

**Comment by ghost** [comment]
We have removed mkbrew.sh
